<?php

namespace Disguise;

use Disguise\Commands\DisguiseCommand;
use Disguise\Commands\NickCommand;
use pocketmine\plugin\PluginBase;

class main extends PluginBase
{

    public function onEnable()
    {
      $this->regCommands();
      $this->getServer()->getLogger()->info("Disguise Plugin Enabled By FrenchWW!");
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public function regCommands()
    {
       $this->getServer()->getCommandMap()->register("disguise", new DisguiseCommand($this));
       $this->getServer()->getCommandMap()->register("nick", new NickCommand($this));
    }

}